### ISSUE TITLE
Warning from Bhagavad Gita API

### ISSUE THREAD

**Issue by PtPrashantTripathi** [pranjulknit/Everyday_Gita#4]
https://github.com/pranjulknit/Everyday_Gita/blob/8da90b7657538e7b5b9037651d41f123be30f277/script.js#L1

Its not a best practice to expose api keys like this
You should be aware of it right

I wanted you to remove this key from public repo

This is a warning cause your are clearly violating policy https://docs.bhagavadgitaapi.in/terms-and-conditions

@PtPrashantTripathi
Owner of BHAGVADGITAAPI

**Comment by pranjulknit** [comment]
I have hide It.
 Thank you.
